### PR TITLE
parse date of mock data properly

### PR DESCRIPTION
**Pull request by felixheck**
The mock data export formatted `date` (real date object) as `date.$date` (string representation). 
That fix reverts that formatting.

### CODE REVIEW

**Review by codeofsumit — CHANGES_REQUESTED** [review]
The problem is not the parsing. The problem is the mock data. The format is like that because of the mongoDB export - in the real codebase, the date is changed directly after the query to the usual date format: yyyy-MM-dd

{
  date: "2020-10-10"
}

A better way to fix this is to change the mock data for proper formats.

**Comment by felixheck** [comment]
@codeofsumit that way?

**Comment by codeofsumit** [comment]
@felixheck yes but also for quotes, no?

**Comment by felixheck** [comment]
quotes have been exported differently..not sure why but looks correct

**Comment by codeofsumit** [comment]
Ah yes, because i took the activities straight from mongo, quotes from a node log

**Pull request merged**
